name: Morning checklist email

on:
  workflow_dispatch: {}
  schedule:
    # 01:30 UTC = 07:00 IST
    - cron: '30 1 * * *'

jobs:
  send-email:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      BASE: ${{ secrets.BACKEND_URL }}
      API_KEY: ${{ secrets.BACKEND_API_KEY }}
      PLAN: ${{ secrets.PLAN_ID }}
    steps:
      - name: Call /ops/send_daily_email
        run: |
          set -euxo pipefail
          PLAN_ID="${PLAN:-default}"
          for i in 1 2 3; do
            curl -sfS "$BASE/ops/send_daily_email?plan_id=$PLAN_ID&span=3" \
              -H "x-api-key: $API_KEY" && break || sleep 10
          done
